### ISSUE TITLE
Children are not removed from UIStackView in live reload after reload.

### ISSUE THREAD

**Issue by matoushybl** [Brightify/ReactantUI#20]

**Comment by TadeasKriz** [comment]
This is a problem of all containers, not just `UIStackView`. If the container has `field` attribute, it doesn't get recreated on reload and keeps all its previous children.

**Comment by matoushybl** [comment]
Proposed approach is to try tagging the views that are added to containers by LiveUI.

**Comment by matoushybl** [comment]
Fixed in 0.3.0.
