### ISSUE TITLE
Project README

### ISSUE THREAD

**Issue by josefdolezal** [Brightify/ReactantUI#29]
Hey @brightify! Thanks for the library, the live reload feature is 💯. I know the docs are available [here](https://docs.reactant.tech/reactant-ui/introduction.html), but it would be great to have some notes also here.

For now, I think that installation guide, swift version compatibility and quick contribution guide (wasn't easy to find up-to-date branch 🤔) are enough informations to begin with. Ping me if you need a hand on this one, I would be happy to help!

**Comment by TadeasKriz** [comment]
Great idea, I completely forgot we don't have a README file here, thanks!

**Comment by matoushybl** [comment]
README was merged to master.
