### ISSUE TITLE
Build error while building from source

### ISSUE THREAD

**Issue by josefdolezal** [Brightify/ReactantUI#30]
Hey @Brightify! I was trying to build the command line tool from source using `swift build`, however there were some build errors. It looks like there is a problem with Swift version used for the build. The source requires Swift 4.0 but the package is defined as 3.0 (with the `.swift-version` file). Therefore the build fails.

### Proposal
* Update the `.swift-version` to require Swift 4.0.
* Remove `Package.pins` since it's replaced with `Package.resolved`.
* Update dependencies to the latest version.
* Update manifest (`Package.swift`) to V4 syntax.

If you are ok with my proposal, I can start working on it 👨‍💻

**Comment by TadeasKriz** [comment]
Definitely a great idea! Didn’t notice that before, thank you.

**Comment by josefdolezal** [comment]
Fixed in #31.
