### ISSUE TITLE
Decide whether to crash or use UIView for elements not supported on tvOS.

### ISSUE THREAD

**Issue by matoushybl** [Brightify/ReactantUI#59]

**Comment by matoushybl** [comment]
@TadeasKriz What do you think about this? Crashing would make it impossible to reuse some layouts from iOS on tvOS, however replacing views with UIView does not make sense. Making some elements unavailable on tvOS is not a solution either as neither generated code or live UI would work with reused layouts.

**Comment by TadeasKriz** [comment]
I'd show an error in Live and Exit with status code 1 and an error describing what was wrong.

**Comment by matoushybl** [comment]
It has been fixed in Live, however it does not work in generator since `#if os(tvOS)` doesn't work there.

**Comment by matoushybl** [comment]
Fixed in 0.3.0.
