### ISSUE TITLE
There should be an option for the generator that allows code generation for older swift versions.

### ISSUE THREAD

**Issue by matoushybl** [Brightify/ReactantUI#64]
For example Swift 4.1 brought `targetEnvironment(simulator)` which was immediately used in RUI, however now the generated code won't be usable in Swift 4 projects.

**Comment by hslatman** [comment]
The --swift x.x flag seems to work. Tested it with 4.0 on the current version of master (https://github.com/Brightify/ReactantUI/commit/3bc05339b4bd673bc7e8175a920eb3ffa433282c)
